# config/gpu-menu.conf

# --- Geometry & Position ---
location=center
width=350
height=240

# --- Behavior ---
show=dmenu
insensitive=true
allow_markup=true

# --- UI Layout ---
# Hide the scrollbar for a cleaner look (since you only have a few GPU modes)
hide_scroll=true
no_actions=true

# Force the items to stretch across the whole menu nicely
halign=fill
orientation=vertical
content_halign=fill
